services:
  notify-service:
    build:
      context: .
      dockerfile: microservices/notify/Dockerfile
    environment:
      - AMQP_URL
      - DATABASE_URL
    networks:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_APP_VERSION="beta-1.0.0"
        - VITE_GA_MEASUREMENT_ID="G-1F69Z3FRGG"
    ports:
      - "8000:4000"
    environment:
      - PORT=4000
      - SESSION_SECRET
      - DATABASE_URL
      - BACKEND_URL
      - AMQP_URL
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
    networks:
      - app
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: uptime
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  db:
  rabbitmq_data:
