services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:4000"
    environment:
      - PORT=4000
      - SESSION_SECRET
      - DATABASE_URL
      - URL=http://localhost:8000
      - AMQP_URL=amqp://user:password@rabbitmq
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - GITHUB_CALLBACK_URL
    networks:
      - app
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: uptime
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  db:
  rabbitmq_data:
