name: Deploy Agent

on:
  workflow_dispatch:

jobs:
  deploy-agent:
    name: Publish Agent Docker image to registry
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Shorter SHA
        shell: bash
        run: |
          echo "sha_short=sha_$(git rev-parse --short "${{ github.sha }}")" >> "$GITHUB_ENV"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./agent
          file: ./agent/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: mirailisc/${{ secrets.AGENT_IMAGE_NAME }}:${{ env.sha_short }},  mirailisc/${{ secrets.AGENT_IMAGE_NAME }}:latest
