name: Test Agent

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  agent-build:
    name: Build Agent
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Backend Build
        run: cd agent && pnpm run build

  docker-build-agent:
    name: Build Docker Image (Agent)
    runs-on: ubuntu-latest
    needs: [agent-build]

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker Image
        run: |
          docker build --no-cache -t ${{ secrets.AGENT_IMAGE_NAME }} -f Dockerfile .
