name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  frontend-eslint:
    permissions:
      contents: read
      security-events: write
      actions: read

    uses: KronosMoe/ci-template/.github/workflows/eslint.yml@main
    with:
      custom-run: "cd frontend && pnpm run lint"

  backend-eslint:
    permissions:
      contents: read
      security-events: write
      actions: read

    uses: KronosMoe/ci-template/.github/workflows/eslint.yml@main
    with:
      custom-run: "cd backend && pnpm run lint"

  frontend-build:
    needs: frontend-eslint
    permissions:
      contents: read
      security-events: write
      actions: read

    uses: KronosMoe/ci-template/.github/workflows/build.yml@main
    with:
      custom-run: "cd frontend && pnpm run build"

  backend-build:
    needs: backend-eslint
    permissions:
      contents: read
      security-events: write
      actions: read

    uses: KronosMoe/ci-template/.github/workflows/build.yml@main
    with:
      custom-run: "cd backend && pnpm run prisma:generate && pnpm run build"

  docker-build:
    name: Build Docker Image (Test)
    runs-on: ubuntu-latest
    needs: [frontend-build, backend-build]

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker Image
        run: |
          docker build --no-cache -t ${{ secrets.IMAGE_NAME }} -f Dockerfile .
